# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vvp7QA-zbIaVE75nMlim6V3HQdfTJajE
"""

data = load_wine()
feature_names = data.feature_names

# Load trained model
with open("best_model.pkl", "rb") as file:
    model = pickle.load(file)

# Streamlit UI
st.title("Wine Classification Model Deployment 🍷")
st.write("Enter the wine characteristics to predict its class.")

# Input fields for user
input_values = []
for feature in feature_names:
    value = st.number_input(f"Enter {feature}", step=0.1)
    input_values.append(value)

# Predict button
if st.button("Predict"):
    input_array = np.array(input_values).reshape(1, -1)

    # Standardization (ensure you use the same scaler as training)
    scaler = StandardScaler()
    input_scaled = scaler.fit_transform(input_array)

    prediction = model.predict(input_scaled)
    st.success(f"Predicted Wine Class: {prediction[0]}")